apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  secrets.properties: |
{{ .Values.secrets.properties | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullName" . }}-opts
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  jsec-opts.txt: |
{{ .Values.secrets.jsecOpts | indent 4 }}